version: '3.8'
name: nepremicnine-discord-bot
services:
    nepremicnine-discord-bot:
        image: nepremicnine-discord-bot
        container_name: nepremicnine-discord-bot
        restart: always
        environment:
        - BOT_TOKEN=your_bot_token
        - DB_PATH=/db/nepremicnine.db
        volumes:
        - db:/



volumes:
  db:
    name: nepremicnine-db
