name: nepremicnine-discord-bot
services:
    python-bot:
        build: .
        container_name: nepremicnine-discord-bot
        depends_on:
            - browser
        env_file: ".env"
        command:
            - "python"
        environment:
            - DB_PATH=/db/nepremicnine_db.sqlite
            - CHROME_URL="ws://browser:3000/chromium/playwright"
        volumes:
            - db:/db
    browser:
        image: ghcr.io/browserless/chromium
        container_name: browser
        restart: always
        ports:
            - "3000:3000"



volumes:
  db:
    name: nepremicnine-db
