name: nepremicnine-discord-bot
services:
    python-bot:
        build: .
        env_file: ".env"
        environment:
            - DB_PATH=/db/nepremicnine_db.sqlite
        volumes:
            - db:/db

volumes:
  db:
    name: nepremicnine-db
